# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	bt_addr \
	irsc_util \
	netmgrd \
	qmuxd \
	rmt_storage \
	sct_service \
	ta_qmi_service \
	tad_static \
	Fluid_Bluetooth_cal \
	Fluid_General_cal \
	Fluid_Global_cal \
	Fluid_Handset_cal \
	Fluid_Hdmi_cal \
	Fluid_Headset_cal \
	Fluid_Speaker_cal \
	Liquid_Bluetooth_cal \
	Liquid_General_cal \
	Liquid_Global_cal \
	Liquid_Handset_cal \
	Liquid_Hdmi_cal \
	Liquid_Headset_cal \
	Liquid_Speaker_cal \
	MTP_Bluetooth_cal \
	MTP_General_cal \
	MTP_Global_cal \
	MTP_Handset_cal \
	MTP_Hdmi_cal \
	MTP_Headset_cal \
	MTP_Speaker_cal \
	a225_pfp \
	a225_pm4 \
	a225p5_pm4 \
	a300_pfp \
	a300_pm4 \
	a330_pfp \
	a330_pm4 \
	adsp_b00 \
	adsp_b01 \
	adsp_b02 \
	adsp_b03 \
	adsp_b04 \
	adsp_b05 \
	adsp_b06 \
	adsp_b07 \
	adsp_b08 \
	adsp_b09 \
	adsp_b10 \
	adsp_b11 \
	adsp_b12 \
	adsp_mdt \
	cmnlib_b00 \
	cmnlib_b01 \
	cmnlib_b02 \
	cmnlib_b03 \
	cmnlib_mdt \
	leia_pfp_470 \
	leia_pm4_470 \
	mba_b00 \
	mba_mdt \
	touch_module_id_0x45 \
	touch_module_id_0x48 \
	touch_module_id_0x4d \
	touch_module_id_0x4e \
	tzhdcp_b00 \
	tzhdcp_b01 \
	tzhdcp_b02 \
	tzhdcp_b03 \
	tzhdcp_mdt \
	tzlibasb_b00 \
	tzlibasb_b01 \
	tzlibasb_b02 \
	tzlibasb_b03 \
	tzlibasb_mdt \
	tznautilus_b00 \
	tznautilus_b01 \
	tznautilus_b02 \
	tznautilus_b03 \
	tznautilus_mdt \
	tzsuntory_b00 \
	tzsuntory_b01 \
	tzsuntory_b02 \
	tzsuntory_b03 \
	tzsuntory_mdt \
	venus_b00 \
	venus_b01 \
	venus_b02 \
	venus_b03 \
	venus_b04 \
	venus_mbn \
	venus_mdt \
	bcm4339_aps \
	bcm4339_sta \
	audio.primary.msm8974 \
	copybit.msm8974 \
	nfc_nci.msm8974 \
	libMcClient \
	libMcRegistry \
	libOmxAacEnc \
	libOmxAmrEnc \
	libOmxCore \
	libOmxEvrcEnc \
	libOmxQcelp13Enc \
	libOmxVdec \
	libOmxVenc \
	libc2dcolorconvert \
	libdivxdrmdecrypt \
	libidd \
	libkeyctrl \
	liblights-core \
	libmiscta \
	libnpfinal \
	libpin-cache \
	libprotobuf-c \
	libstagefrighthw \
	libsys-utils \
	libta \
	libvirtual \
	effect_init_params \
	libpn547_fw \
	eglsubAndroid \
	libEGL_adreno \
	libGLESv1_CM_adreno \
	libGLESv2_adreno \
	libq3dtools_adreno \
	sensors.msm8974 \
	libC2D2 \
	libCB \
	libI420colorconvert \
	libOpenCL \
	libOpenVG \
	libQSEEComAPI \
	libRSDriver_adreno \
	libacdbloader \
	libacdbmapper \
	libacdbrtac \
	libadiertac \
	libadreno_utils \
	libadsprpc \
	libaudcal \
	libaudioalsa \
	libc2d2_z180 \
	libc2d30-a3xx \
	libc2d30-a4xx \
	libc2d30 \
	libdiag \
	libdrmdiag \
	libdrmfs \
	libdrmtime \
	libdsi_netctrl \
	libdsnetutils \
	libdsutils \
	libgsl \
	libidl \
	libllvm-qcom \
	libmm-abl-oem \
	libmm-abl \
	libnetmgr \
	libqc-opt \
	libqcci_legacy \
	libqdi \
	libqdp \
	libqmi \
	libqmi_cci \
	libqmi_client_qmux \
	libqmi_common_so \
	libqmi_csi \
	libqmi_csvt_srvc \
	libqmi_encdec \
	libqmiservices \
	libril-qc-qmi-1 \
	librs_adreno \
	librs_adreno_sha1 \
	libsc-a2xx \
	libsc-a3xx \
	libsensor1 \
	libsensor_reg \
	libtime_genoff
