# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	bt_addr \
	hci_qcomm_init \
	irsc_util \
	netmgrd \
	qmuxd \
	rmt_storage \
	sct_service \
	ta_qmi_service \
	wcnss_addr \
	tad_static \
	Bluetooth_cal \
	General_cal \
	Global_cal \
	Hdmi_cal \
	Headset_cal \
	a225_pfp \
	a225_pm4 \
	a225p5_pm4 \
	a300_pfp \
	a300_pm4 \
	a330_pfp \
	a330_pm4 \
	adsp_b00 \
	adsp_b01 \
	adsp_b02 \
	adsp_b03 \
	adsp_b04 \
	adsp_b05 \
	adsp_b06 \
	adsp_b07 \
	adsp_b08 \
	adsp_b09 \
	adsp_b10 \
	adsp_b11 \
	adsp_mdt \
	PS_ASIC \
	RamPatch \
	bdata_bin_sdio \
	bdata_bin_usb \
	fw.ram \
	cmnlib_b00 \
	cmnlib_b01 \
	cmnlib_b02 \
	cmnlib_b03 \
	cmnlib_mdt \
	cpp_firmware_v1_1_1 \
	cpp_firmware_v1_1_6 \
	cpp_firmware_v1_2_0 \
	leia_pfp_470 \
	leia_pm4_470 \
	mba_b00 \
	mba_mdt \
	touch_module_id_0x45 \
	touch_module_id_0x48 \
	touch_module_id_0x49 \
	touch_module_id_0x4d \
	touch_module_id_0x4e \
	touch_module_id_0x4f \
	touch_module_id_0x50 \
	touch_module_id_0x51 \
	touch_module_id_0x57 \
	touch_module_id_0x59 \
	touch_module_id_0x5a \
	touch_module_id_0x5b \
	touch_module_id_0x5c \
	touch_module_id_0x5e \
	touch_module_id_0x5f \
	tzhdcp_b00 \
	tzhdcp_b01 \
	tzhdcp_b02 \
	tzhdcp_b03 \
	tzhdcp_mdt \
	tzlibasb_b00 \
	tzlibasb_b01 \
	tzlibasb_b02 \
	tzlibasb_b03 \
	tzlibasb_mdt \
	tznautilus_b00 \
	tznautilus_b01 \
	tznautilus_b02 \
	tznautilus_b03 \
	tznautilus_mdt \
	tzsuntory_b00 \
	tzsuntory_b01 \
	tzsuntory_b02 \
	tzsuntory_b03 \
	tzsuntory_mdt \
	venus_b00 \
	venus_b01 \
	venus_b02 \
	venus_b03 \
	venus_b04 \
	venus_mbn \
	venus_mdt \
	wcnss_b00 \
	wcnss_b01 \
	wcnss_b02 \
	wcnss_b04 \
	wcnss_b06 \
	wcnss_b07 \
	wcnss_b08 \
	wcnss_b09 \
	wcnss_mdt \
	WCNSS_cfg \
	WCNSS_qcom_cfg \
	WCNSS_qcom_wlan_nv \
	copybit.msm8974 \
	nfc.msm8974 \
	libMcClient \
	libMcRegistry \
	libOmxAacEnc \
	libOmxAmrEnc \
	libOmxCore \
	libOmxEvrcEnc \
	libOmxQcelp13Enc \
	libOmxVdec \
	libOmxVenc \
	libc2dcolorconvert \
	libcnefeatureconfig \
	libdivxdrmdecrypt \
	libidd \
	libkeyctrl \
	libmiscta \
	libmm-omxcore \
	libmmjpeg_interface \
	libnpfinal \
	libpin-cache \
	libprotobuf-c \
	libqomx_core \
	libstagefrighthw \
	libta \
	effect_init_params \
	libpn544_fw \
	eglsubAndroid \
	libEGL_adreno \
	libGLESv1_CM_adreno \
	libGLESv2_adreno \
	libq3dtools_adreno \
	sensors.msm8974 \
	libC2D2 \
	libCB \
	libI420colorconvert \
	libOpenCL \
	libOpenVG \
	libQSEEComAPI \
	libRSDriver_adreno \
	libacdbloader \
	libacdbmapper \
	libacdbrtac \
	libadiertac \
	libadreno_utils \
	libadsprpc \
	libbtnv \
	libc2d2_z180 \
	libc2d30-a3xx \
	libc2d30-a4xx \
	libc2d30 \
	libcneapiclient \
	libcneqmiutils \
	libcneutils \
	libdiag \
	libdrmfs \
	libdsi_netctrl \
	libdsnetutils \
	libdsutils \
	libfastcvadsp_stub \
	libfastcvopt \
	libgsl \
	libidl \
	liblistenhardware \
	libllvm-qcom \
	libmm-abl-oem \
	libmm-abl \
	libmm-color-convertor \
	libmmjpeg \
	libmmqjpeg_codec \
	libnetmgr \
	libqc-opt \
	libqcci_legacy \
	libqcgesture \
	libqdi \
	libqdp \
	libqmi \
	libqmi_cci \
	libqmi_client_qmux \
	libqmi_common_so \
	libqmi_csi \
	libqmi_csvt_srvc \
	libqmi_encdec \
	libqmiservices \
	libqomx_jpegdec \
	libqomx_jpegenc \
	libril-qc-qmi-1 \
	librpmb \
	librs_adreno \
	librs_adreno_sha1 \
	libsc-a2xx \
	libsc-a3xx \
	libsensor1 \
	libsensor_reg \
	libsubsystem_control \
	libtime_genoff \
	libulp2 \
	libxml
