# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	hci_qcomm_init \
	irsc_util \
	netmgrd \
	qmiproxy \
	qmuxd \
	sct_service \
	sensors \
	MTP_Bluetooth_cal \
	MTP_General_cal \
	MTP_Global_cal \
	MTP_Handset_cal \
	MTP_Hdmi_cal \
	MTP_Headset_cal \
	MTP_Speaker_cal \
	QRD_Bluetooth_cal \
	QRD_General_cal \
	QRD_Global_cal \
	QRD_Handset_cal \
	QRD_Hdmi_cal \
	QRD_Headset_cal \
	QRD_Speaker_cal \
	a225_pfp \
	a225_pm4 \
	a225p5_pm4 \
	a300_pfp \
	a300_pm4 \
	a330_pfp \
	a330_pm4 \
	adsp_b00 \
	adsp_b01 \
	adsp_b02 \
	adsp_b03 \
	adsp_b04 \
	adsp_b05 \
	adsp_b06 \
	adsp_b07 \
	adsp_b08 \
	adsp_b09 \
	adsp_b10 \
	adsp_b11 \
	adsp_b12 \
	adsp_mdt \
	cmnlib_b00 \
	cmnlib_b01 \
	cmnlib_b02 \
	cmnlib_b03 \
	cmnlib_mdt \
	cpp_firmware_v1_1_1 \
	cpp_firmware_v1_1_6 \
	cpp_firmware_v1_2_0 \
	cyttsp4_fw \
	leia_pfp_470 \
	leia_pm4_470 \
	mba_b00 \
	mba_mdt \
	modem_b00 \
	modem_b01 \
	modem_b02 \
	modem_b03 \
	modem_b04 \
	modem_b05 \
	modem_b08 \
	modem_b10 \
	modem_b11 \
	modem_b13 \
	modem_b14 \
	modem_b15 \
	modem_b16 \
	modem_b17 \
	modem_b18 \
	modem_b19 \
	modem_b20 \
	modem_b21 \
	modem_b22 \
	modem_b25 \
	modem_b26 \
	modem_b27 \
	modem_mdt \
	tzhdcp_b00 \
	tzhdcp_b01 \
	tzhdcp_b02 \
	tzhdcp_b03 \
	tzhdcp_mdt \
	tzlibasb_b00 \
	tzlibasb_b01 \
	tzlibasb_b02 \
	tzlibasb_b03 \
	tzlibasb_mdt \
	tzsuntory_b00 \
	tzsuntory_b01 \
	tzsuntory_b02 \
	tzsuntory_b03 \
	tzsuntory_mdt \
	venus_b00 \
	venus_b01 \
	venus_b02 \
	venus_b03 \
	venus_b04 \
	venus_mbn \
	venus_mdt \
	wcnss_b00 \
	wcnss_b01 \
	wcnss_b02 \
	wcnss_b04 \
	wcnss_b06 \
	wcnss_b07 \
	wcnss_b08 \
	wcnss_b09 \
	wcnss_mdt \
	WCNSS_cfg \
	WCNSS_qcom_cfg \
	WCNSS_qcom_wlan_nv \
	copybit.msm8226 \
	nfc_nci_pn547.msm8226 \
	libkeyctrl \
	libmm-omxcore \
	libmmjpeg_interface \
	libpin-cache \
	libqomx_core \
	libvirtual \
	scsi_wait_scan \
	wlan \
	libpn547_fw \
	sensors.msm8226 \
	libCommandSvc \
	libExtendedExtractor \
	libFileMux \
	libOmxAacDec \
	libOmxAmrwbplusDec \
	libOmxMux \
	libStDrvInt \
	libTimeService \
	libWVStreamControlAPI_L3 \
	libacdbloader \
	libacdbmapper \
	libacdbrtac \
	libadiertac \
	libaudcal \
	libaudioalsa \
	libbtnv \
	libcneqmiutils \
	libconfigdb \
	libdsi_netctrl \
	libdsnetutils \
	libdsucsd \
	libdsutils \
	libfastcvadsp_stub \
	libidl \
	libjpegdhw \
	libjpegehw \
	liblbs_core \
	liblisten \
	liblistenhardware \
	libmm-abl-oem \
	libmmhttpstack \
	libmmiipstreammmihttp \
	libmmipl \
	libmmipstreamaal \
	libmmipstreamnetwork \
	libmmipstreamsourcehttp \
	libmmipstreamutils \
	libmmjpeg \
	libmmosal \
	libmmparser \
	libmmqjpeg_codec \
	libmmrtpdecoder \
	libmmrtpencoder \
	libmmwfdinterface \
	libmmwfdsinkinterface \
	libmmwfdsrcinterface \
	libnetmgr \
	liboi_sbc_decoder \
	libqcci_legacy \
	libqdi \
	libqdp \
	libqmi \
	libqmi_cci \
	libqmi_client_qmux \
	libqmi_common_so \
	libqmi_csi \
	libqmi_csvt_srvc \
	libqmi_encdec \
	libqmiservices \
	libqomx_jpegdec \
	libqomx_jpegenc \
	libril-qc-qmi-1 \
	libsensor1 \
	libsensor_reg \
	libsubsystem_control \
	libthermalclient \
	libthermalioctl \
	libtime_genoff \
	libwfdcommonutils \
	libwfdmmsink \
	libwfdmmsrc \
	libwfdmmutils \
	libwfdrtsp \
	libwfdsm \
	libwfduibcinterface \
	libwfduibcsink \
	libwfduibcsinkinterface \
	libwfduibcsrc \
	libwfduibcsrcinterface \
	libwvdrm_L3 \
	libxml
