# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	QmiGateDaemon \
	btnvtool \
	hci_qcomm_init \
	irsc_util \
	netmgrd \
	qmiproxy \
	qmuxd \
	sct_service \
	MTP_Bluetooth_cal \
	MTP_General_cal \
	MTP_Global_cal \
	MTP_Handset_cal \
	MTP_Hdmi_cal \
	MTP_Headset_cal \
	MTP_Speaker_cal \
	QRD_Bluetooth_cal \
	QRD_General_cal \
	QRD_Global_cal \
	QRD_Handset_cal \
	QRD_Hdmi_cal \
	QRD_Headset_cal \
	QRD_Speaker_cal \
	VY52_VY53_Bluetooth_cal \
	VY52_VY53_General_cal \
	VY52_VY53_Global_cal \
	VY52_VY53_Handset_cal \
	VY52_VY53_Hdmi_cal \
	VY52_VY53_Headset_cal \
	VY52_VY53_Speaker_cal \
	VY55_VY56_Bluetooth_cal \
	VY55_VY56_General_cal \
	VY55_VY56_Global_cal \
	VY55_VY56_Handset_cal \
	VY55_VY56_Hdmi_cal \
	VY55_VY56_Headset_cal \
	VY55_VY56_Speaker_cal \
	VY58_VY59_Bluetooth_cal \
	VY58_VY59_General_cal \
	VY58_VY59_Global_cal \
	VY58_VY59_Handset_cal \
	VY58_VY59_Hdmi_cal \
	VY58_VY59_Headset_cal \
	VY58_VY59_Speaker_cal \
	VY58_VY59_AP_Bluetooth_cal \
	VY58_VY59_AP_General_cal \
	VY58_VY59_AP_Global_cal \
	VY58_VY59_AP_Handset_cal \
	VY58_VY59_AP_Hdmi_cal \
	VY58_VY59_AP_Headset_cal \
	VY58_VY59_AP_Speaker_cal \
	VY58_VY59_SP_Bluetooth_cal \
	VY58_VY59_SP_General_cal \
	VY58_VY59_SP_Global_cal \
	VY58_VY59_SP_Handset_cal \
	VY58_VY59_SP_Hdmi_cal \
	VY58_VY59_SP_Headset_cal \
	VY58_VY59_SP_Speaker_cal \
	Signedrompatch_v20 \
	Signedrompatch_v21 \
	Signedrompatch_v24 \
	a225_pfp \
	a225_pm4 \
	a225p5_pm4 \
	a300_pfp \
	a300_pm4 \
	a330_pfp \
	a330_pm4 \
	cmnlib_b00 \
	cmnlib_b01 \
	cmnlib_b02 \
	cmnlib_b03 \
	cmnlib_mdt \
	cpp_firmware_v1_1_1 \
	cpp_firmware_v1_1_6 \
	cpp_firmware_v1_2_0 \
	leia_pfp_470 \
	leia_pm4_470 \
	nfc_test \
	tzhdcp_b00 \
	tzhdcp_b01 \
	tzhdcp_b02 \
	tzhdcp_b03 \
	tzhdcp_mdt \
	tzlibasb_b00 \
	tzlibasb_b01 \
	tzlibasb_b02 \
	tzlibasb_b03 \
	tzlibasb_mdt \
	tzsuntory_b00 \
	tzsuntory_b01 \
	tzsuntory_b02 \
	tzsuntory_b03 \
	tzsuntory_mdt \
	venus_b00 \
	venus_b01 \
	venus_b02 \
	venus_b03 \
	venus_b04 \
	venus_mbn \
	venus_mdt \
	WCNSS_cfg \
	WCNSS_qcom_cfg \
	WCNSS_qcom_wlan_nv \
	persist_index \
	rlxservice_xml \
	copybit.msm8226 \
	sensors.msm8226 \
	libmm-omxcore \
	libmmjpeg_interface \
	libqmi_gate \
	libqmigatenvjni \
	libqmigateservice \
	libqomx_core \
	libvirtual \
	libyasalgo \
	scsi_wait_scan \
	wlan \
	rlxservice_jar \
	libpn547_fw \
	libCommandSvc \
	libDiagService \
	libExtendedExtractor \
	libFileMux \
	libOmxAacDec \
	libOmxAmrwbplusDec \
	libOmxMux \
	libOmxWmaDec \
	libStDrvInt \
	libSubSystemShutdown \
	libTimeService \
	libWVStreamControlAPI_L3 \
	libacdbloader \
	libacdbmapper \
	libacdbrtac \
	libadiertac \
	libaudcal \
	libaudioalsa \
	libbtnv \
	libcneqmiutils \
	libconfigdb \
	libdsi_netctrl \
	libdsnetutils \
	libdsucsd \
	libdsutils \
	libfastcvadsp_stub \
	libidl \
	libjpegdhw \
	libjpegehw \
	liblbs_core \
	liblisten \
	liblistenhardware \
	liblistenjni \
	libloc_ext \
	liblocationservice \
	libmm-abl-oem \
	libmmhttpstack \
	libmmiipstreammmihttp \
	libmmipl \
	libmmipstreamaal \
	libmmipstreamnetwork \
	libmmipstreamsourcehttp \
	libmmipstreamutils \
	libmmjpeg \
	libmmosal \
	libmmparser \
	libmmqjpeg_codec \
	libmmrtpdecoder \
	libmmrtpencoder \
	libmmwfdinterface \
	libmmwfdsinkinterface \
	libmmwfdsrcinterface \
	libnetmgr \
	liboi_sbc_decoder \
	libqcci_legacy \
	libqdi \
	libqdp \
	libqmi \
	libqmi_cci \
	libqmi_client_qmux \
	libqmi_common_so \
	libqmi_csi \
	libqmi_csvt_srvc \
	libqmi_encdec \
	libqmiservices \
	libqomx_jpegdec \
	libqomx_jpegenc \
	libril-qc-qmi-1 \
	libril-qcril-hook-oem \
	libsensor1 \
	libsensor_reg \
	libsensor_test \
	libsensor_thresh \
	libsensor_user_cal \
	libsubsystem_control \
	libsurround_proc \
	libthermalclient \
	libthermalioctl \
	libtime_genoff \
	libwfdcommonutils \
	libwfdmmsink \
	libwfdmmsrc \
	libwfdmmutils \
	libwfdnative \
	libwfdrtsp \
	libwfdsm \
	libwfduibcinterface \
	libwfduibcsink \
	libwfduibcsinkinterface \
	libwfduibcsrc \
	libwfduibcsrcinterface \
	libwvdrm_L3 \
	libxml \
	surround_sound_headers
